./codatest.sh: line 9: python3: command not found
python3: can't open file 'runtest.py': [Errno 2] No such file or directory
Running tests
Specifying application psi4
Specifying input file ./input.runtime.coda
Specifying number of nodes for testing
Specifying number of cores per node for testing
Successfully created the directory /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/SC20Test/Test/fliu67-testflight-coda-1-28-20200603_17_06_23
Successfully created the directory /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/SC20Test/Test/fliu67-testflight-coda-1-28-20200603_17_06_23/psi4
Successfully copied from /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/Application/Input/psi4 to /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/SC20Test/Test/fliu67-testflight-coda-1-28-20200603_17_06_23/psi4
qsub -------------------2431.sched-testflight-coda.pace.gatech.edu


Get system info successfully
1233.049
Close the database connection
Running tests
Specifying application psi4
Specifying input file ./input.runtime.coda
Specifying number of nodes for testing
Specifying number of cores per node for testing
Successfully created the directory /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/SC20Test/Test/fliu67-testflight-coda-1-28-20200604_15_18_54
Successfully created the directory /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/SC20Test/Test/fliu67-testflight-coda-1-28-20200604_15_18_54/psi4
Successfully copied from /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/Application/Input/psi4 to /storage/coda1/pace-admins/fliu67/Project/local/PACE-ProvBench/SC20Test/Test/fliu67-testflight-coda-1-28-20200604_15_18_54/psi4
qsub -------------------2485.sched-testflight-coda.pace.gatech.edu


Get system info successfully
1152.162
Close the database connection

real	153m59.187s
user	21m47.974s
sys	88m10.093s
